### ISSUE TITLE
Library initial fetch not works

### ISSUE THREAD

**Issue by nielsd** [Manuel-K/shruthi-editor#6]
Hiho Manuel,

very nice work so far! But i can't use it's potential because i did not get the library fetched initially. i clicked "fetch" (i.e. while the first patch "init" is active) and the librarian counts "received valid patches and sequences, but the list shows "init" or the name of the currently selected (on the shruti / Phoenix (TubeOhm)) patch. I.e. if i selected "junon" the library filled with "junon".

The device is on it's own MIDI iface (MIDI face from a access virus TI2), chan 3 (with 4pm) and MIDI out is "ctrl" (full seems to lead to "unknown" sysex data).

It seems any patch number counter or similar is not rising anywhere while fetching the library. 

any ideas?

many many thanks in advance,

Niels.

**Comment by Manuel-K** [comment]
Hi Niels,

sorry for taking so long; I'm quite busy at the moment.

I've never tested the editor with the TubeOhm patch and I'm not sure if any of the library functions has been tested with a non-default channel setting. Either could be the cause of the problem. If you want to try it yourself, I would suggest that you switch the midi channels.

I'm sure that the patch number is increased, but it seems that the program change messages don't work.

By the way, which operation system do you use?

Manuel

**Comment by nielsd** [comment]
Hi Manual,


many thanks for your reply.

I've asked TubeOhm which told me that they use the standard build with no 
further patches (except splash image). The only "speciality" is the lack of 
the typically used bootloader (i.e. to play in firmware by MIDI).

Yes, it seems if the patch select increment is not "working". If i click onto 
another library entry (with "init") it seems working to switch the preset 
(i've overwritten a few patches this way with init patches without recognizing 
it...).

I use Mac OS (newest) on a current Mac Book Pro. With other MIDI synths / 
devices i have no prob (i have many...)

Is it possible that the editor work's "to fast" (the MIDI of shruti / with the 
amtel seems slow)? Is there any var or default i can try to change in the 
sources to slow down / delay the transfers or similiar?

I have another MIDI interface ("a more cheap" USB2MIDI one) which i can test, 
but the external access virus MIDI interface is robust / reliable otherwise.

many thanks for any idea.

many thanks for any help / idea / hint.
best regards,


Niels.


Am Dienstag, 1. März 2016, 22:56:01 schrieb Manuel K:
> Hi Niels,

**Comment by Manuel-K** [comment]
It seems that you have found an unitialized variable in the library code. To make matters worse the editor didn't relay the channel change to the library. I've never encountered the problem because I only use one midi device and leave the shruthi in omni mode…

 Can you test 4061e9e on your end?

**Comment by nielsd** [comment]
Hi Manuel,


i think i got it now.


After switching anything to channel 0 / omni between MacOSX and the shruti the library got fetched without problems. No changes onto the code was required. I knewed that shruti „requires“ a full MIDI interface for it’s own to „work properly“ with sysex stuff,  but my studio setup requires other channels because my persons motor fader is hard wired at chan 1 (which sends some stuff anytime) and i work with some software which isn’t able to filter MIDI input properly. So i have to fiddle that in another way.

sorry for the noise so far.

btw: Do you still active work on this editor and / or plan further todo stuff? I’m new to qt and even DAW plugin development, but generally interested in bringing in some of my time if it makes any sense further. The sequencer is one thing which spikes into my eyes as a part which could get more „intuitivity“ (but possibly more difficult when divine into qt…ß) but may be…

Secondly i fetched a air programmer to get into the shruti firmware if this helps further.

Many many thanks for your coll work and invested time so far!


cheerioh,


Niels.

> Am 02.03.2016 um 16:48 schrieb Manuel K <notifications@github.com>:
> 
> It seems that you have found an unitialized variable in the library code. To make matters worse the editor didn't relay the channel change to the library. I've never encountered the problem because I only use one midi device and leave the shruthi in omni mode…

**Comment by Manuel-K** [comment]
> After switching anything to channel 0 / omni between MacOSX and the shruti the library got fetched without problems. No changes onto the code was required. I knewed that shruti „requires“ a full MIDI interface for it’s own to „work properly“ with sysex stuff, but my studio setup requires other channels because my persons motor fader is hard wired at chan 1 (which sends some stuff anytime) and i work with some software which isn’t able to filter MIDI input properly. So i have to fiddle that in another way.

So you didn't try my changes? I think I fixed the problems, but it would be great if you could test it as well. If they work, I will release a new version.

> btw: Do you still active work on this editor and / or plan further todo stuff? I’m new to qt and even DAW plugin development, but generally interested in bringing in some of my time if it makes any sense further. The sequencer is one thing which spikes into my eyes as a part which could get more „intuitivity“ (but possibly more difficult when divine into qt…ß) but may be…

I don't have any plans for the editor at the moment. I know that the sequence editor isn't that intuitive, but this seemed the easiest way to implement it, because the ui is close to the internal workings. I thought about writing a piano roll style interface, but I wasn't that sure if there is enough demand to warrant the time investment.

> Secondly i fetched a air programmer to get into the shruti firmware if this helps further.
The main problem during firmware development are the space constraints. I've tried it several times with different versions of the toolchain components, but never menaged to get the same (or even similar) size of the binary. Without optimizations my firmware version were too large. I've managed to decrease the size with optimizations but that opens a new can of worms.

Achso. Reden zwei Deutsche auf Englisch. Sehr praktisch. ;)

**Comment by nielsd** [comment]
> Am 04.03.2016 um 22:26 schrieb Manuel K <notifications@github.com>:
> 
> So you didn't try my changes? I think I fixed the problems, but it would be great if you could test it as well. If they work, I will release a new version.
tried now - seems to work properly too.
> 
> Achso. Reden zwei Deutsche auf Englisch. Sehr praktisch. ;)
Yo, deshalb oben nochmal für die internationalen Mitleser auf "englisch“.

Ich habe zwar nicht im detail nachvollzogen, was Du nochmal geändert hast - der Abruf der Library scheint nun aber noch etwas „rückenfreier“ zu erfolgen (Timings o.ä. geändert?). Hauptsache, es geht nun.

Der Editor ist echt hilfreich. In Kürze wollt ich mir noch einen zweiten Shruti mit Steiner/Parker (bisher 4pm) bauen und betreiben. Die Möglichkeit mit dem Editor mehrere Shrutis (was augenscheinlich gar nicht so selten ist) betreiben zu können, wäre daher lustig. Allerdings kann ich nicht einschätzen, wieviele aktive User dieses Editors es sonst noch gibt. Habe zwar auch mit dem shreditor beta 8 rumgespielt, aber der hat lediglich in punkto sequencer mehr Ergonomie. Die QT-typsiche Oberfläche gefällt mir hier wesentlich besser. ß)

**Comment by Manuel-K** [comment]
> Ich habe zwar nicht im detail nachvollzogen, was Du nochmal geändert hast - der Abruf der Library scheint nun aber noch etwas „rückenfreier“ zu erfolgen (Timings o.ä. geändert?). Hauptsache, es geht nun.

Der Editor hat die Midikanal-Einstellung respektiert, aber alles, was mit der Bibliothek zu tun hat, hat die Einstellung nicht mitbekommen und auf einem zufälligen Midi-Kanal gearbeitet. Deshalb hat er immer die selben Daten geholt, da er den Programmwechsel-Befehl auf dem falschen Kanal gesendet hat.

> Die Möglichkeit mit dem Editor mehrere Shrutis (was augenscheinlich gar nicht so selten ist) betreiben zu können, wäre daher lustig.

Wie gesagt. Das sollte jetzt funktionieren.

**Comment by Manuel-K** [comment]
Should be done.

@nielsd: Bitte eine Mitteilung an mich, wenn es weitere Probleme gibt.

**Comment by nielsd** [comment]
Geht - Danke!!! (dachte hätte ich bereits gemeldet, sorry)...

**Comment by Manuel-K** [comment]
@nielsd:
Könntest du bitte nachsehen, ob ich mit der Aktualisierung von RtMidi in https://github.com/Manuel-K/shruthi-editor/releases/tag/v1.02 irgendetwas OS X spezifisches kaputt gemacht habe?

Und ich hätte da noch einen Anschlag: Wärst du bereit, eine Version mit statisch eingebundenem Qt5 zur Verfügung zu stellen?
